/**
 * UFs disponíveis na consulta pública de cidades (Jetlu + Lopesul).
 */
export const UFS_ATENDIDAS = [
  'BA',
  'ES',
  'GO',
  'MS',
  'MT',
  'PA',
  'PE',
  'PR',
  'RJ',
  'RS',
  'SC',
  'SP',
  'TO',
]

export const UF_MAPA_HREF = {
  acre: 'AC',
  alagoas: 'AL',
  amapa: 'AP',
  amazonas: 'AM',
  bahia: 'BA',
  ceara: 'CE',
  distritofederal: 'DF',
  espiritosanto: 'ES',
  goias: 'GO',
  maranhao: 'MA',
  matogrosso: 'MT',
  matogrossodosul: 'MS',
  minasgerais: 'MG',
  para: 'PA',
  paraiba: 'PB',
  parana: 'PR',
  pernambuco: 'PE',
  piaui: 'PI',
  riodejaneiro: 'RJ',
  riograndedonorte: 'RN',
  riograndedosul: 'RS',
  rondonia: 'RO',
  roraima: 'RR',
  santacatarina: 'SC',
  saopaulo: 'SP',
  sergipe: 'SE',
  tocantins: 'TO',
}
